<?php

namespace Database\Seeders;

use App\Models\QuestionChoice;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QuestionEPPSChoiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pilihanA =
            // A
            [
                'Saya suka menolong teman-teman saya, apabila mereka dalam kesulitan.',
                'Saya ingin mengetahui bagimana pandangan orang-orang besar, mengenai berbagai masalah yang menarik perhatian saya.',
                'Saya menghendaki bahwa setiap pekerjaan tulis saya teliti, rapi dan tersusun dengan baik.',
                'Saya suka menceritakan cerita-cerita yang lucu dan lelucon-lelucon waktu pesta.',
                'Saya ingin dapat berbuat sekehendak hati saya.',
                'Saya ingin dapat memecahkan teka-teki dan persoalan-persoalan yang sukar bagi orang lain.',
                'Saya ingin mengalami pembaharuan dan perubahan dalam kehidupan saya sehari-hari.',
                'Saya suka merencanakan dan mengatur detail-detail dari setiap pekerjaan yang harus saya lakukan.',
                'Saya ingin orang-orang memperhatikan dan memberikan komentar mengenai penampilan saya di depan umum.',
                'Saya suka mengelakkan situasi-situasi yang mengharapkan saya melakukan hal-hal dengan cara konvensional (kebiasaan yang umum dilakukan orang).',
                //10
                'Saya ingin menjadi seorang ahli yang diakui dalam suatu pekerjaan, jabatan atau bidang khusus.',
                'Saya ingin mengetahui bagaimana pandangan orang-orang besar/ahli, mengenai berbagai masalah yang menarik perhatian saya.',
                'Saya suka menyelesaikan setiap pekerjaan atau tugas yang telah saya mulai',
                'Saya suka bercerita kepada orang-orang lain tentang petualangan-petualangan saya dan hal-hal aneh yang pernah saya alami.',
                'Saya ingin tidak tergantung dari orang lain dalam menentukan apa yang akan saya lakukan.',
                'Saya ingin bisa mengerjakan segala sesuatu lebih baik daripada orang-orang lain.',
                'Saya suka mengikuti adat-istiadat dan menghindarkan melakukan hal-hal yang mungkin dianggap tidak wajar oleh orang-orang yang saya hormati.',
                'Saya ingin agar hidup saya teratur sedemikian rupa, sehingga berjalan lancar dan tanpa banyak perubahan-perubahan dalam rencana saya.',
                'Saya suka membaca buku-buku dan sandiwara, terutama yang berkisar sekitar masalah seks.',
                'Saya	suka	mengecam	orang-orang	yang	kedudukannya	memegang kekuasaan.',
                //20
                'Saya suka menyelesaikan tugas-tugas yang dianggap orang lain sebagai tugas yang membutuhkan keterampilan dan usaha.',
                'Saya suka memuji orang yang saya kagumi.',
                'Saya suka menyimpan surat-surat, bon-bon, dan kertas-kertas lain secara tersusun rapi dan menurut sistem tertentu.',
                'Saya suka mengajukan pertanyaan-pertanyaan yang menurut saya tidak seorangpun akan dapat menjawabnya.',
                'Saya menjadi sedemikian marahnya, sehingga rasanya ingin melemparkan dan merusak barang-barang.',
                'Saya ingin berhasil dalam apa yang saya lakukan.',
                'Saya suka mengikuti petunjuk-petunjuk dan melakukan apa yang diharapkan orang dari diri saya.',
                'Saya menghendaki bahwa setiap pekerjaan tulis saya teliti, rapi dan tersusun dengan baik. ',
                'Saya suka menceritakan cerita-cerita lucu dan lelucon-lelucon waktu pesta.',
                'Saya ingin berbuat sekehendak hati saya.',
                // 30
                'Saya ingin dapat memecahkan teka teki dan persoalan-persoalan yang sukar bagi orang lain.',
                'Saya suka menerima pimpinan dari orang-orang yang saya kagumi.',
                'Saya suka makan saya teratur dan ada waktu-waktu tertentu untuk makan.',
                'Saya suka mengatakan hal yang dianggap lucu dan cerdas oleh orang lain.',
                'Saya ingin merasa bebas untuk melakukan apa yang saya kehendaki.',
                'Saya suka menyelesaikan tugas-tugas yang dianggap orang lain sebagai tugas yang membutuhkan keterampilan dan usaha.',
                'Dalam merencanakan sesuatu, saya ingin mendapat saran-saran dari orang- orang yang pendapatnya saya hormati.',
                'Saya ingin agar hidup saya teratur sedemikian rupa sehingga berjalan lancar dan tanpa banyak perubahan-perubahan dalam rencana saya.',
                'Saya suka menjadi pusat perhatian, apabila syaa ada dalam suatu kelompok.',
                'Saya suka mengelakkan situasi-situasi yang mengharapkan saya melakukan hal-hal dengan konvensional (kebiasaan yang umum dilakukan orang).',
                // 40
                'Saya ingin menulis roman atau sandiwara yang hebat.',
                'Apabila saya berada dalam kelompok saya suka menerima pimpinan orang lain dalam memutuskan apa yang akan dilakukan oleh kelompok tersebut.',
                'Saya suka menyimpan surat-surat, bon-bon, dan kertas-kertas lainnya secara tersusun rapi dan menurut sistem tertentu.',
                'Saya suka mengajukan pertanyaan-pertanyaan yang menurut saya tidak seorangpun akan dapat menjawabnya.',
                'Saya suka mengelakkan tanggung jawab dan kewajiban-kewajiban.',
                'Saya ingin menjadi ahli yang diakui dalam pekerjaan, jabatan atau bidang khusus.',
                'Saya suka membaca riwayat orang-orang besar.',
                'Saya suka merencanakan dan mengatur detail-detail dari setiap pekerjaan yang harus saya lakukan.',
                'Saya suka menggunakan kata-kata yang maknanya seringkali tidak diketahui oleh orang lain.',
                'Saya	suka	mengecam	orang-orang	yang	kedudukannya	memegang kekuasaan.',
                // 50
                'Saya suka melakukan pekerjaan apa saja terbaik mungkin.',
                'Saya ingin mengetahui bagimana pandangan orang-orang besar mengenai berbagai masalah yang menarik perhatian saya.',
                'Saya suka membuat rencana sebelum memulai pekerjaan yang sulit.',
                'Saya suka bercerita kepada orang-orang lain tentang petualangan-petualangan saya dan hal-hal aneh yang pernah saya alami.',
                'Saya suka menyatakan pendapat saya tentang berbagai hal.',
                'Saya ingin bisa mengerjakan segala sesuatu lebih baik daripada orang-orang lain.',
                'Saya suka mengikuti adat-istiadat dan menghindarkan melakukan hal-hal yang mungkin dianggap tidak wajar oleh orang-orang yang saya hormati',
                'Sebelum memulai sesuatu pekerjaan saya ingin pekerjaan itu teratur dan terencanakan.',
                'Saya ingin orang-orang memperhatikan dan memberikan komentar mengenai penampilan saya di depan umum.',
                'Saya ingin tidak tergantung dari orang lain dalam menentukan apa yang akan saya lakukan.',
                // 60
                'Saya ingin bisa mengatakan bahwa saya telah melakukan dengan baik suatu pekerjaan yang sulit.',
                'Saya suka menyatakan kepada atasan saya bahwa mereka telah melakukan sesuatu pekerjaan yang baik, apabila menurut pendapat saya memang demikian keadaannya.',
                'Jika saya akan bepergian, saya senang apabila segala sesuatunya telah direncanakan sebelumnya.',
                'Saya kadang-kadang suka melakukan hal-hal hanya untuk melihat bagaimana pengaruhnya terhadap orang lain.',
                'Saya suka melakukan hal-hal yang dianggap orang lain tidak sesuai dengan adat kebiasaan.',
                'Saya ingin menyelesaikan sesuatu yang sangat penting artinya.',
                'Saya suka memuji orang yang saya kagumi.',
                'Saya ingin barang-barang saya tersusun rapi dan teratur di atas meja atau di dalam ruang kerja saya.',
                'Saya suka berbicara tentang hal-hal yang saya capai.',
                'Saya ingin melakukan hal-hal dengan cara saya sendiri tanpa menghiraukan apa yang mungkin dipikirkan orang lain.',
                // 70
                'Saya ingin menulis roman atau sandiwara yang hebat.',
                'Apabila saya berada dalam kelompok saya suka menerima pimpinan orang lain dalam memutuskan apa yang akan dilakukan oleh kelompok tersebut',
                'Saya ingin agar hidup saya teratur sedemikian rupa, sehingga berjalan lancar dan tanpa banyak perubahan-perubahan dalam rencana saya',
                'Saya suka mengajukan pertanyaan-pertanyaan yang menurut saya tidak seorangpun akan dapat menjawabnya',
                'Saya suka mengelakkan tanggung jawab dan kewajiban-kewajiban',
                'Saya ingin loyal terhadap teman-teman saya',
                'Saya suka mengamat-amati bagaimana perasaan orang lain dalam suatu keadaan tertentu',
                'Saya ingin teman-teman memberi dorongan kepada saya bila saya menghadapi kegagalan',
                'Saya ingin menjadi salah seorang pemimpin dalam organisasi-organisasi atau kelompok-kelompok dimana saya menjadi anggotanya',
                'Bila keadaan kurang menguntungkan bagi saya, maka saya merasa bahwa saya harus lebih disalahkan daripada orang lain',
                //80
                'Saya suka melakukan sesuatu untuk teman-teman saya',
                'Saya suka untuk menempatkan diri saya ditempat orang lain, dan membayangkan bagaimana perasaan saya apabila saya dalam keadaan atau situasi yang sama',
                'Saya ingin agar teman-teman saya menunjukkan simpati dan pengertian bila saya mengalami kesukaran-kesukaran',
                'Apabila saya bekerja dalam suatu panitia, saya ingin ditunjuk atau dipilih sebagai ketuanya',
                'Apabila saya melakukan sesuatu hal yang salah, saya merasa bahwa untuk itu saya harus dihukum',
                'Saya suka dalam melakukan atau menjalani segala sesuatu bersama-sama dengan teman-teman',
                'Saya ingin memahami bagimana perasaan teman-teman saya dalam menghadapi berbagai masalah',
                'Saya ingin diperlakukan dengan ramah oleh teman-teman saya',
                'Saya ingin dianggap sebagai pemimpin oleh orang-orang lain',
                'Saya merasa bahwa pilu hati dan kesusahan yang telah saya alami, lebih banyak membawa kebaikan daripada kerugian bagi saya',
                //90
                'Saya ingin mempunyai ikatan perasaan yang kuat dengan teman teman saya',
                'Saya suka merenungkan kepribadian teman-teman saya dan mencoba mengerti apa yang menyebabkan mereka mempunyai kepribadian yang demikian',
                'Saya ingin agar teman-teman saya meributkan tentang diri saya, apabila mendapatkan cedera atau sakit',
                'Saya suka mengatakan pada orang-orang lain bagimana mereka harus melakukan pekerjaan mereka',
                'Saya merasa canggung ditengah-tengah orang-orang lain yang saya anggap sebagai atasan saya',
                'Saya lebih suka mengerjakan sesuatu bersama-sama dengan teman-teman saya daripada sendirian',
                'Saya suka mempelajari dan menganalisa tingkah laku orang-orang lain',
                'Saya ingin teman-teman saya merasa kasihan pada saya apabila saya sedang sakit',
                'Sedapat mungkin saya ingin membimbing dan mengarahkan tindakan atau perbuatan orang lain',
                'Saya merasa bahwa dalam banyak hal, saya kalah bila dibandingkan dengan orang-orang lain',
                // 100
                'Saya ingin berhasil dalam apa yang saya lakukan',
                'Saya suka menganalisa perasaan-perasaan saya dan sebab-sebab mengapa saya melakukan sesuatu',
                'Saya ingin agar teman-teman saya membantu saya bila saya mengalami kesulitan',
                'Saya suka memperdebatkan pendirian saya bila diserang oleh orang-orang lain',
                'Saya merasa bersalah, apabila saya telah melakukan sesuatu yang saya ketahui keliru',
                'Saya suka dalam melakukan atau menjalani segala sesuatu bersama-sama dengan teman-teman',
                'Saya suka menerima pimpinan dari orang-orang yang saya kagumi',
                'Saya ingin agar teman-teman saya dengan gembira memberikan pertolongan pertolongan kecil kepada saya',
                'Bila saya berada dalam suatu kelompok, saya ingin menentukan apa yang akan kami kerjakan',
                'Saya lebih suka mengalah dan menghindarkan perkelahian daripada memaksakan kemauan saya',
                // 110
                'Saya suka membuat teman-teman baru',
                'Saya suka menilai orang berdasarkan sebab-sebab mengapa mereka melakukan sesuatu, bukan berdasar apa yang sesungguhnya mereka  lakukan',
                'Saya ingin agar hidup saya teratur sedemikian rupa, sehingga berjalan lancar dan tanpa banyak perubahan-perubahan dalam rencana saya',
                'Saya senang untuk diminta menyelesaikan pertentangan-pertentangan atau perselisihan-perselisihan',
                'Saya merasa bahwa saya harus mengakui hal-hal yang telah saya lakukan dan saya anggap salah',
                'Saya lebih suka mengerjakan sesuatu bersama-sama dengan teman-teman saya daripada sendirian',
                'Saya suka merenungkan kepribadian teman-teman saya dan mencoba mengerti apa yang menyebabkan mereka mempunyai kepribadian yang demikian',
                'Saya ingin agar teman-teman saya bersimpati terhadap saya dan menghibur saya bila saya bersusah hati',
                'Saya suka mengajukan pertanyaan-pertanyaan yang menurut saya tidak seorangpun akan dapat menjawabnya',
                'Saya merasa canggung ditengah-tengah orang-orang lain yang saya anggap sebagai atasan saya',
                // 120
                'Saya suka bergaul dalam kelompok yang para anggotanya akrab dan bersahabat satu sama lainnya',
                'Saya suka menganalisa perasaan-perasaan orang lain dan sebab-sebab mengapa mereka melakukan sesuatu',
                'Saya ingin teman-teman saya merasa kasihan pada saya apabila saya sedang sakit',
                'Saya ingin dapat membujuk dan mempengaruhi orang lain untuk melakukan apa yang saya kehendaki',
                'Saya suka mengecam orang-orang yang kedudukannya memegang kekuasaan',
                'Saya suka bergaul dalam kelompok yang para anggotanya akrab dan bersahabat satu sama lainnya',
                'Saya suka menganalisa perasaan-perasaan saya dan sebab-sebab mengapa saya melakukan sesuatu',
                'Saya ingin agar teman-teman saya membantu saya bila saya mengalami kesulitan',
                'Saya ingin menjadi salah seorang pemimpin dalam organisasi-organisasi kelompok yang saya masuki',
                'Saya merasa bahwa pilu hati dan kesusahan yang telah saya alami, lebih banyak membawa kebaikan daripada kerugian bagi saya',
                // 130
                'Saya lebih suka mengerjakan sesuatu bersama-sama dengan teman-teman saya daripada sendirian',
                'Saya suka merenungkan kepribadian teman-teman saya dan mencoba mengerti apa yang menyebabkan mereka mempunyai kepribadian yang demikian',
                'Saya ingin agar teman-teman saya menunjukkan simpati dan pengertian bila saya mengalami kesukaran-kesukaran',
                'Saya suka memperdebatkan pendirian saya bila diserang oleh orang-orang lain',
                'Saya lebih suka mengalah dan menghindarkan perkelahian daripada memaksakan kemauan saya',
                'Saya suka melakukan sesuatu untuk teman-teman saya',
                'Saya suka menganalisa perasaan-perasaan orang lain dan sebab-sebab mengapa mereka melakukan sesuatu',
                'Saya suka memberi pertolongan-pertolongan kecil kepada teman-teman saya',
                'Saya ingin dianggap sebagai pemimpin oleh orang-orang lain',
                'Apabila saya melakukan sesuatu hal yang salah, saya merasa bahwa untuk itu saya harus dihukum',
                // 140
                'Saya ingin loyal terhadap teman-teman saya',
                'Saya suka meramalkan bagaimana teman-teman saya akan bertindak dalam berbagai situasi',
                'Saya ingin teman teman saya menunjukkan rasa sayang mereka terhadap saya',
                'Bila saya berada dalam suatu kelompok, saya ingin menentukan apa yang akan kami kerjakan',
                'Saya merasa sedih akan ketidakmampuan saya untuk menghadapi berbagai macam keadaan',
                'Saya suka berkirim surat kepada teman-teman saya',
                'Saya suka meramalkan bagimana teman-teman saya akan bertindak dalam berbagai situasi',
                'Saya ingin agar teman-teman saya meributkan tentang diri saya, apabila mendapatkan cedera atau sakit',
                'Saya suka menyatakan kepada orang lain bagaimana mereka harus melakukan pekerjaan mereka',
                'Saya merasa bahwa dalam banyak hal, saya kalah bila dibandingkan dengan orang-orang lain',
                // 150
                'Saya suka menolong teman-teman saya, apabila mereka dalam kesulitan',
                'Saya suka bepergian melihat-lihat daerah pedalaman',
                'Saya suka bekerja keras pada tiap pekerjaan yang saya hadapi',
                'Saya suka bepergian dengan lawan jenis saya yang menarik (bagi laki-laki dengan wanita;bagi wanita dengan laki-laki)',
                'Sayas suka membaca berita-berita surat kabar tentang pembunuhan- pembunuhan dan lain-lain perbuatan kekerasan',
                'Saya suka memberi pertolongan-pertolongan kecil kepada teman-teman saya',
                'Saya ingin mengalami pembaharuan dan perubahan dalam kehidupan saya sehari-hari',
                'Saya suka bekerja sampai jauh malam untuk menyelesaikan suatu pekerjaan',
                'Saya suka nafsu saya terangsang',
                'Rasa rasanya ingin membalas dendam bila seseorang menghina saya',
                // 160
                'Saya suka bermurah hati terhadap teman-teman saya',
                'Saya suka bertemu dengan orang-orang baru',
                'Saya suka menyelesaikan setiap pekerjaan atau tugas yang telah saya mulai',
                'Saya ingin dianggap punya daya tarik ﬁsik oleh orang-orang dari lawan jenis saya',
                'Saya suka mengatakan kepada orang-orang lain bagaimana pendapat saya mengenai mereka',
                'Saya suka berlaku ramah tehadap teman-teman saya',
                'Saya suka mencoba pekerjaan yang baru dan berbeda-beda, daripada melakukan pekerjaan yang sama dan terus menerus',
                'Saya suka bertahan menghadapi suatu pekerjaan atau masalah, sekalipun tampaknya seolah-olah saya tak akan berhasil',
                'Saya suka membaca buku-buku dan sandiwara, terutama yang berkisar sekitar masalah seks',
                'Saya rasanya ingin menyalahkan orang lain bila keadaannya kurang menguntungkan saya',
                // 170
                'Saya suka menunjukkan simpati saya kepada teman-teman saya bila mereka mendapat cedera atau sakit',
                'Saya suka makan di restoran-restoran yang baru atau asing',
                'Saya ingin menyelesaikan pekerjaan satu persatu sebelum memulai yang lain',
                'Saya suka ikut serta dalam diskusi-diskusi tentang seks dan aktiﬁtas seksuil',
                'Saya menjadi sedemikian marahnya, sehingga rasanya ingin melemparkan dan merusak barang-barang',
                'Saya suka menolong teman-teman saya, apabila mereka dalam kesulitan',
                'Saya suka mengerjakan hal-hal yang baru dan berbeda-beda',
                'Bila saya harus melakukan suatu tugas, saya ingin mengerjakannya sampai selesai',
                'Saya suka bepergian dengan lawan jenis saya yang menarik (bagi laki-laki dengan wanita;bagi wanita dengan laki-laki)',
                'Saya suka menyerang pendirian-pendirian yang bertentangan dengan pendirian saya',
                //180
                'Saya suka bermurah hati terhadap teman teman saya',
                'Saya suka makan di restoran-restoran yang baru atau asing',
                'Saya suka bekerja sampai jauh malam untuk menyelesaikan suatu pekerjaan',
                'Saya suka nafsu saya terangsang',
                'Saya rasanya ingin memperolok-olok orang-orang yang melakukan hal-hal yang saya anggap bodoh',
                'Saya suka memaafkan teman-teman saya yang menyakiti hati saya',
                'Saya suka bereksperimen dalam mencoba hal-hal yang baru',
                'Saya suka mengerjakan teka-teki atau memecahkan persoalan-persoalan sampai selesai',
                'Saya ingin dianggap punya daya tarik ﬁsik oleh orang-orang dari lawan jenis saya',
                'Saya rasanya ingin mengecam seseorang di muka umum bila orang itu patut menerimanya',
                // 190
                'Saya suka berlaku ramah tehadap teman-teman saya',
                'Saya lebih suka mencoba pekerjaan-pekerjaan yang baru dan lain daripada terus menerus melakukan pekerjaan yang sama',
                'Saya suka menyelesaikan setiap pekerjaan atau tugas yang telah saya mulai',
                'Saya suka ikut serta dalam diskusi-diskusi tentang seks dan aktiﬁtas seksuil',
                'Saya menjadi sedemikian marahnya, sehingga rasanya ingin melemparkan dan merusak barang-barang',
                'Saya suka berlaku sangat ramah terhadap teman teman saya',
                'Saya suka berkeliling di pedalaman dan tinggal di berbagai tempat',
                'Saya suka bertahan menghadapi suatu pekerjaan atau masalah, sekalipun tampaknya seolah-olah saya tak akan berhasil',
                'Saya suka membaca buku-buku dan sandiwara, terutama yang berkisar sekitar masalah seks',
                'Saya rasanya ingin menyalahkan orang lain bila keadaannya kurang menguntungkan saya',
                // 200
                'Saya suka melakukan pekerjaan apa saja terbaik mungkin',
                'Saya suka mengerjakan hal-hal yang baru dan berbeda-beda',
                'Bila saya harus melakukan suatu tugas, saya ingin mengerjakannya sampai selesai',
                'Saya suka ikut dalam aktivitas-aktivitas sosial bersama-sama dengan orang- orang dari lawan jenis saya',
                'Saya suka menyerang pendirian-pendirian yang bertentangan dengan pendirian saya',
                'Saya suka memperlakukan orang lain dengan ramah dan simpatik',
                'Saya suka mengikuti adat-istiadat dan menghindarkan melakukan hal-hal yang mungkin dianggap tidak wajar oleh orang-orang yang saya hormati',
                'Saya suka bekerja keras pada tiap pekerjaan yang saya hadapi',
                'Saya mempunyai keinginan untuk mencium orang yang menarik dari lawan jenis saya',
                'Saya rasanya ingin menghardik orang lain bila saya berbeda pendapat dengan mereka',
                // 210
                'Saya suka menolong orang-orang lain, yang tidak begitu beruntung apabila dibandingkan dengan keadaan saya',
                'Saya suka berkeliling di pedalaman dan tinggal di berbagai tempat',
                'Jika saya akan bepergian, saya senang apabila segala sesuatunya telah direncanakan sebelumnya',
                'Saya mudah jatuh cinta pada seseorang dari lawan jenis saya',
                'Saya suka mengatakan kepada orang-orang lain bagimana pendapat saya mengenai mereka',
                'Saya suka memberi pertolongan-pertolongan kecil kepada teman-teman saya',
                'Saya suka bertemu dengan orang-orang baru',
                'Saya ingin mengerjakan teka-teki atau memecahkan persoalan-persoalan sampai selesai',
                'Saya suka berbicara tentang hal-hal yang telah saya capai',
                'Saya rasanya ingin memperolok orang-orang yang melakukan hal-hal yang saya anggap bodoh',
                // 220
                'Saya ingin teman-teman saya mempercayai saya dan menceritakan kesulitan- kesulitan mereka kepada saya',
                'Saya suka mengikuti mode baru',
                'Saya ingin menghindarkan diganggu bila saya sedang bekerja',
                'Saya suka mendengarkan atau menceritakan lelucon-lelucon yang terutama berkisar soal seks',
                'Saya suka mengelakkan tanggung jawab dan kewajiban-kewajiban'
            ];
        $pilihanB =
            [
                'Saya ingin melakukan apa saja sebaik mungkin.',
                'Saya ingin menyelesaikan sesuatu yang sangat penting artinya.',
                'Saya ingin menjadi seorang ahli yang diakui dalam suatu pekerjaan, jabatan atau bidang yang khusus.',
                'Saya ingin menulis roman atau sandiwara yang hebat.',
                'Saya ingin bisa mengatakan bahwa saya telah melakukan dengan baik suatu pekerjaan yang sulit.',
                'Saya suka mengikuti petunjuk-petunjuk dan melakukan apa yang diharapkan orang lain dari saya',
                'Saya suka menyatakan kepada atasan saya bahwa mereka telah melakukan sesuatu pekerjaan yang baik, apabila menurut pendapat saya memang demikian adanya.',
                'Saya suka mengikuti petunjuk-petunjuk dan melakukan apa yang diharapkan orang dari diri saya',
                'Saya suka membaca riwayat hidup orang-orang besar.',
                'Saya suka membaca riwayat hidup orang-orang besar',
                //10
                'Sebelum memulai sesuatu pekerjaan saya ingin pekerjaan itu teratur dan terencanakan.',
                'Jika saya akan bepergian, saya senang apabila segala sesuatunya telah direncanakan sebelumnya',
                'Saya ingin barang-barang saya tersusun rapi dan teratur di atas meja atau di dalam ruang kerja saya.',
                'Saya suka makan saya teratur dan ada waktu-waktu tertentu untuk makan.',
                'Saya ingin barang-barang saya tersusun rapi dan teratur di atas meja atau di dalam ruang kerja saya.',
                'Saya suka menceritakan cerita-cerita lucu dan lelucon-lelucon waktu pesta.',
                'Saya suka berbicara tentang hal-hal yang telah saya capai.',
                'Saya suka bercerita kepada orang-orang lain tentang petualangan-petualangan saya dan hal-hal aneh yang pernah saya alami.',
                'Saya suka menjadi pusat perhatian, apabila saya ada di dalam suatu kelompok.',
                'Saya suka menggunakan kata-kata yang maknanya seringkali tidak diketahui oleh orang lain',
                // 20
                'Saya ingin dapat berbuat sekehendak hati saya',
                'Saya ingin merasa bebas untuk melakukan apa yang saya kehendaki',
                'Saya ingin tidak tergantung dari orang lain dalam menentukan apa yang akan saya lakukan',
                'Saya suka mengecam orang-orang yang kedudukannya memegang kekuasaan',
                'Saya suka mengelakkan tanggung jawab dan kewajiban-kewajiban',
                'Saya suka membuat teman-teman baru',
                'Saya ingin mempunyai ikatan perasaan yang kuat dengan teman teman saya',
                'Saya ingin membuat teman sebanyak mungkin',
                'Saya suka berkirim surat pada teman-teman saya',
                'Saya suka dalam melakukan atau menjalani segala sesuatu bersama-sama dengan teman-teman',
                // 30
                'Saya suka menilai orang berdasarkan sebab-sebab mengapa mereka melakukan sesuatu, bukan berdasar apa yang sesungguhnya mereka lakukan',
                'Saya ingin memahami bagimana perasaan teman-teman saya dalam menghadapi berbagai masalah',
                'Saya suka mempelajari dan menganalisa tingkah laku orang-orang lain',
                'Saya suka untuk menempatkan diri saya ditempat orang lain, dan membayangkan bagaimana perasaan saya apabila saya dalam keadaan atau situasi yang sama',
                'Saya suka mengamat-amati bagaimana perasaan orang lain dalam satu keadaan tertentu',
                'Saya ingin teman-teman saya memberi dorongan-dorongan kepada saya bila saya menghadapi kegagalan',
                'Saya ingin diperlakukan dengan ramah oleh teman-teman saya',
                'Saya ingin teman-teman saya merasa kasihan pada saya apabila saya sedang sakit',
                'Saya ingin agar teman-teman saya meributkan tentang diri saya, apabila mendapatkan cedera atau sakit',
                'Saya ingin agar teman-teman saya bersimpati terhadap saya dan menghibur saya bila saya bersusah hati',
                // 40
                'Apabila saya bekerja dalam suatu panitia, saya ingin ditunjuk atau dipilih sebagai ketuanya',
                'Sedapat mungkin saya ingin membimbing dan mengarahkan tindakan atau perbuatan orang lain',
                'Saya ingin menjadi salah seorang pemimpin dalam organisasi-organisasi atau kelompok-kelompok dimana saya menjadi anggotanya',
                'Saya suka mengatakan pada orang-orang lain bagimana mereka harus melakukan pekerjaan mereka',
                'Saya senang untuk diminta menyelesaikan pertentangan-pertentangan atau perselisihan-perselisihan',
                'Saya merasa bersalah, apabila saya telah melakukan sesuatu yang saya ketahui keliru',
                'Saya merasa bahwa saya harus mengakui hal-hal yang telah saya lakukan dan saya anggap salah',
                'Bila keadaan kurang menguntungkan bagi saya, maka saya merasa bahwa saya harus lebih disalahkan daripada orang lain',
                'Saya merasa bahwa dalam banyak hal, saya kalah bila dibandingkan dengan orang-orang lain',
                'Saya merasa canggung ditengah-tengah orang-orang lain yang saya anggap sebagai atasan saya',
                // 50
                'Saya suka menolong orang-orang lain, yang tidak begitu beruntung apabila dibandingkan dengan keadaan saya',
                'Saya suka bermurah hati terhadap teman teman saya',
                'Saya suka memberi pertolongan-pertolongan kecil kepada teman-teman saya',
                'Saya ingin teman-teman saya mempercayai saya dan menceritakan kesulitan- kesulitan mereka kepada saya',
                'Saya suka memaafkan teman-teman saya yang menyakiti hati saya',
                'Saya suka makan di restoran-restoran yang baru atau asing',
                'Saya suka mengikuti mode-mode baru',
                'Saya suka bepergian melihat-lihat daerah pedalaman',
                'Saya suka berkeliling di pedalaman dan tinggal di berbagai tempat',
                'Saya suka mengerjakan hal-hal yang baru dan berbeda-beda',
                // 60
                'Saya suka bekerja keras pada tiap pekerjaan yang saya hadapi',
                'Saya ingin menyelesaikan pekerjaan satu-persatu sebelum memulai yang lainnya',
                'Saya suka mengerjakan teka-teki atau memecahkan persoalan-persoalan sampai selesai',
                'Saya suka bertahan menghadapi suatu pekerjaan atau masalah, sekalipun tampaknya seolah-olah saya tak akan berhasil',
                'Saya ingin bekerja berjam-jam tanpa diganggu',
                'Saya mempunyai keinginan untuk mencium orang yang menarik dari lawan jenis saya',
                'Saya ingin dianggap punya daya tarik ﬁsik oleh orang-orang dari lawan jenis saya',
                'Saya mudah jatuh cinta pada seseorang dari lawan jenis saya',
                'Saya suka mendengarkan atau menceritakan lelucon-lelucon yang terutama berkisar soal seks',
                'Saya suka membaca buku-buku dan sandiwara, terutama yang berkisar sekitar masalah seks',
                // 70
                'Saya suka menyerang pendirian-pendirian yang bertentangan dengan pendirian saya',
                'Saya rasanya ingin mengecam seseorang di muka umum bila orang itu patut menerimanya',
                'Saya menjadi sedemikian marahnya, sehingga rasanya ingin melemparkan dan merusak barang-barang',
                'Saya suka mengatakan kepada orang-orang lain bagimana pendapat saya mengenai mereka',
                'Saya rasanya ingin memperolok-olok orang-orang yang melakukan hal-hal yang saya anggap bodoh',
                'Saya ingin melakukan pekerjaan apa saja sebaik mungkin',
                'Saya ingin bisa mengatakan bahwa saya telah melakukan dengan baik sesuatu pekerjaan yang sulit',
                'Saya ingin berhasil dalam apa yang saya lakukan',
                'Saya ingin bisa mengerjakan segala sesuatu lebih baik daripada orang-orang lain',
                'Saya suka memecahkan teka teki dan persoalan-persoalan yang sukar bagi orang lain',
                // 80
                'Dalam merencanakan sesuatu, saya ingin mendapat saran-saran dari orang-orang yang pendapatnya saya hormati',
                'Saya suka menyatakan kepada atasan saya bahwa mereka telah melakukan sesuatu pekerjaan yang baik, apabila menurut pendapat saya memang demikian adanya',
                'Saya suka menerima pempinan dari orang-orang yang saya kagumi',
                'Apabila saya berada dalam kelompok saya suka menerima pimpinan orang lain dalam memutuskan apa yang akan dilakukan oleh kelompok tersebut',
                'Saya suka mengikuti adat-istiadat dan menghindarkan melakukan hal-hal yang mungkin dianggap tidak wajar oleh orang-orang yang saya hormati',
                'Saya suka membuat perencanaan sebelum mulai pekerjaan yang sulit',
                'Jika saya akan bepergian, saya senang apabila segala sesuatunya telah direncanakan sebelumnya',
                'Sebelum memulai sesuatu pekerjaan saya ingin pekerjaan itu teratur dan terencanakan',
                'Saya suka menyimpan surat-surat, bon-bon, dan kertas-kertas lain secara tersusun rapi dan menurut sistem tertentu',
                'Saya ingin agar hidup saya teratur sedemikian rupa, sehingga berjalan lancar dan tanpa banyak perubahan-perubahan dalam rencana saya',
                // 90
                'Saya suka mengatakan hal yang dianggap lucu dan cerdas oleh orang lain',
                'Saya kadang-kadang suka melakukan hal-hal hanya untuk melihat bagaimana pengaruhnya terhadap orang lain',
                'Saya suka berbicara tentang hal-hal yang telah saya capai',
                'Saya suka menjadi pusat perhatian, apabila saya ada di dalam suatu kelompok',
                'Saya suka menggunakan kata-kata yang maknanya seringkali tidak diketahui oleh orang lain',
                'Saya suka menyatakan pendapat saya tentang berbagai hal',
                'Saya suka melakukan hal-hal yang dianggap orang lain tidak sesuai dengan adat kebiasaan',
                'Saya suka mengelakkan situasi-situasi yang mengharapkan saya melakukan hal-hal dengan cara konvensional (kebiasaan yang umum dilakukan orang)',
                'Saya ingin melakukan hal-hal dengan cara saya sendiri tanpa menghiraukan apa yang mungkin dipikirkan orang lain',
                'Saya suka mengelakkan tanggung jawab dan kewajiban-kewajiban',
                // 100
                'Saya suka membuat teman-teman baru',
                'Saya ingin melakukan sesuatu untuk teman-teman saya',
                'Saya suka melakukan sesuatu untuk teman-teman saya',
                'Saya suka berkirim surat kepada teman-teman saya',
                'Saya ingin mempunyai ikatan perasaan yang kuat dengan teman teman saya',
                'Saya suka menganalisa perasaan-perasaan saya dan sebab-sebab mengapa saya melakukan sesuatu',
                'Saya ingin memahami bagimana perasaan teman-teman saya dalam menghadapi berbagai masalah',
                'Saya suka menilai orang berdasarkan sebab-sebab mengapa mereka melakukan sesuatu, bukan berdasar apa yang sesungguhnya mereka lakukan',
                'Saya suka meramalkan bagimana teman-teman saya akan bertindak dalam berbagai situasi',
                'Saya suka menganalisa perasaan-perasaan orang lain dan sebab-sebab mengapa mereka melakukan sesuatu',
                // 110
                'Saya ingin agar teman-teman saya membantu saya bila saya mengalami kesulitan',
                'Saya ingin teman-teman saya banyak menujukkan rasa sayang mereka terhadap saya',
                'Saya ingin teman-teman saya merasa kasihan pada saya apabila saya sedang sakit',
                'Saya ingin agar teman-teman saya dengan gembira memberikan pertolongan- pertolongan kecil kepada saya',
                'Saya ingin agar teman-teman saya bersimpati terhadap saya dan menghibur saya bila saya bersusah hati',
                'Saya suka memperdebatkan pendirian saya bila diserang oleh orang-orang lain',
                'Saya ingin dapat membujuk dan mempengaruhi orang lain untuk melakukan apa yang saya kehendaki',
                'Bila saya berada dalam suatu kelompok, saya ingin menentukan apa yang akan kami kerjakan',
                'Saya suka menyatakan kepada orang lain bagaimana mereka harus melakukan pekerjaan mereka',
                'Sedapat mungkin saya ingin membimbing dan mengarahkan tindakan atau perbuatan orang lain',
                // 120
                'Saya merasa bersalah, apabila saya telah melakukan sesuatu yang saya ketahui keliru',
                'Saya merasa sedih akan ketidakmampuan saya untuk menghadapi berbagai macam keadaan',
                'Saya lebih suka mengalah dan menghindarkan perkelahian daripada memaksakan kemauan saya',
                'Saya merasa sedih akan ketidakmampuan saya untuk menghadapi berbagai macam keadaan',
                'Saya merasa canggung ditengah-tengah orang-orang lain yang saya anggap sebagai atasan saya',
                'Saya suka menolong teman-teman saya, apabila mereka dalam kesulitan',
                'Saya suka menunjukkan simpati saya kepada teman-teman saya bila mereka mendapat cedera atau sakit',
                'Saya suka memperlakukan orang lain dengan ramah dan simpatik',
                'Saya suka menunjukkan simpati saya kepada teman-teman saya bila mereka mendapat cedera atau sakit',
                'Saya suka berlaku ramah tehadap teman-teman saya',
                // 130
                'Saya suka bereksperimen dalam mencoba hal-hal yang baru',
                'Saya suka mencoba pekerjaan yang baru dan berbeda-beda, daripada melakukan pekerjaan yang sama dan terus menerus',
                'Saya suka bertemu dengan orang-orang baru',
                'Saya ingin mengalami pembaharuan dan perubahan dalam kehidupan saya sehari hari',
                'Saya suka berkeliling di pedalaman dan tinggal di berbagai tempat',
                'Bila saya harus melakukan suatu tugas, saya ingin mengerjakannya sampai selesai',
                'Saya ingin menghindarkan gangguan bila saya sedang bekerja',
                'Saya suka bekerja sampai jauh malam untuk menyelesaikan suatu pekerjaan',
                'Saya ingin bekerja berjam-jam tanpa diganggu',
                'Saya suka bertahan menghadapi suatu pekerjaan atau masalah, sekalipun tampaknya seolah-olah saya tak akan berhasil',
                // 140
                'Saya suka bepergian dengan lawan jenis saya yang menarik (bagi laki-laki dengan wanita;bagi wanita dengan laki-laki)',
                'Saya suka ikut serta dalam diskusi-diskusi tentang seks dan aktiﬁtas seksuil',
                'Saya suka nafsu saya terangsang',
                'Saya suka ikut dalam aktivitas-aktivitas sosial bersama-sama dengan orang-orang dari lawan jenis saya',
                'Saya suka membaca buku-buku dan sandiwara, terutama yang berkisar sekitar masalah seks',
                'Saya suka membaca berita-berita surat kabar tentang pembunuhan-pembunuhan dan lain-lain perbuatan kekerasan',
                'Saya suka menyerang pendirian-pendirian yang bertentangan dengan pendirian saya',
                'Saya rasanya ingin menyalahkan orang lain bila keadaannya kurang menguntungkan saya',
                'Rasa rasanya ingin membalas dendam bila seseorang menghina saya',
                'Saya rasanya ingin menghardik orang lain bila saya berbeda pendapat dengan mereka',
                // 150
                'Saya suka melakukan pekerjaan apa saja sebaik mungkin',
                'Saya suka menyelesaikan tugas-tugas yang dianggap orang lain sebagai tugas yang membutuhkan keterampilan dan usaha',
                'Saya ingin menyelesaikan sesuatu yang sangat penting artinya',
                'Saya ingin berhasil dalam apa yang saya lakukan',
                'Saya ingin menulis roman atau sandiwara yang hebat',
                'Dalam merencanakan sesuatu, saya ingin mendapat saran-saran dari orang-orang yang pendapatnya saya hormati',
                'Saya suka menyatakan kepada atasan saya bahwa mereka telah melakukan sesuatu pekerjaan yang baik, apabila menurut pendapat saya memang demikian adanya',
                'Saya suka memuji orang yang saya kagumi',
                'Saya suka menerima pimpinan dari orang-orang yang saya kagumi',
                'Apabila saya berada dalam kelompok saya suka menerima pimpinan orang lain dalam memutuskan apa yang akan dilakukan oleh kelompok tersebut',
                // 160
                'Saya suka membuat rencana sebelum memulai pekerjaan yang sulit',
                'Saya menghendaki bahwa setiap pekerjaan tulis saya teliti, rapi dan tersusun dengan baik',
                'Saya ingin barang-barang saya tersusun rapi dan teratur di atas meja atau di dalam ruang kerja saya',
                'Saya suka merencanakan dan mengatur detail-detail dari setiap pekerjaan yang harus saya lakukan',
                'Saya suka makan saya teratur dan ada waktu-waktu tertentu untuk makan',
                'Saya suka mengatakan hal yang dianggap lucu dan cerdas oleh orang lain',
                'Saya kadang-kadang suka melakukan hal-hal hanya untuk melihat bagaimana pengaruhnya terhadap orang lain',
                'Saya ingin orang-orang memperhatikan dan memberikan komentar mengenai penampilan saya di depan umum',
                'Saya suka menjadi pusat perhatian, apabila saya ada di dalam suatu kelompok',
                'Saya suka mengajukan pertanyaan-pertanyaan yang menurut saya tidak seorangpun akan dapat menjawabnya',
                // 170
                'Saya suka mengatakan pendapat saya tentang berbagai hal',
                'Saya suka melakukan hal-hal yang dianggap orang lain tidak sesuai dengan adat kebiasaan',
                'Saya ingin merasa bebas untuk melakukan apa yang saya kehendaki',
                'Saya ingin melakukan hal-hal dengan cara saya sendiri tanpa menghiraukan apa yang mungkin dipikirkan orang lain',
                'Saya suka mengelakkan tanggung jawab dan kewajiban-kewajiban',
                'Saya ingin loyal terhadap teman-teman saya',
                'Saya suka membuat teman teman baru',
                'Saya suka bergaul dalam kelompok yang para anggotanya akrab dan bersahabat satu sama lainnya',
                'Saya ingin membuat teman sebanyak mungkin',
                'Saya suka berkirim surat pada teman-teman saya',
                // 180
                'Saya suka mengamat-amati bagaimana perasaan orang lain dalam satu keadaan tertentu',
                'Saya suka untuk menempatkan diri saya ditempat orang lain, dan membayangkan bagaimana perasaan saya apabila saya dalam keadaan atau situasi yang sama',
                'Saya ingin memahami bagaimana perasaan teman-teman saya dalam menghadapi berbagai masalah',
                'Saya suka mempelajari dan menganalisa tingkah laku orang-orang lain',
                'Saya suka meramalkan bagimana teman-teman saya akan bertindak dalam berbagai situasi',
                'Saya ingin teman-teman saya memberi dorongan-dorongan kepada saya bila saya menghadapi kegagalan',
                'Saya ingin agar teman-teman saya menunjukkan simpati dan pengertian bila saya mengalami kesukaran-kesukaran',
                'Saya ingin diperlakukan dengan ramah oleh teman-teman saya',
                'Saya ingin teman-teman saya banyak menujukkan rasa sayang mereka terhadap saya',
                'Saya ingin agar teman-teman saya meributkan tentang diri saya, apabila mendapatkan cedera atau sakit',
                // 190
                'Saya ingin dianggap sebagai pemimpin oleh orang-orang lain',
                'Apabila saya bekerja dalam suatu panitia, saya ingin ditunjuk atau dipilih sebagai ketuanya',
                'Saya ingin dapat membujuk dan mempengaruhi orang lain untuk melakukan apa yang saya kehendaki',
                'Saya senang untuk diminta menyelesaikan pertentangan-pertentangan atau perselisihan-perselisihan',
                'Saya suka menyatakan kepada orang lain bagaimana mereka harus melakukan pekerjaan mereka',
                'Bila keadaan kurang menguntungkan bagi saya, maka saya merasa bahwa saya harus lebih disalahkan daripada orang lain',
                'Apabila saya melakukan sesuatu hal yang salah, saya merasa bahwa untuk itu saya harus dihukum',
                'Saya merasa bahwa pilu hati dan kesusahan yang telah saya alami, lebih banyak membawa kebaikan daripada kerugian bagi saya',
                'Saya merasa bahwa saya harus mengakui hal-hal yang telah saya lakukan dan saya anggap salah',
                'Saya merasa bahwa dalam banyak hal, saya kalah bila dibandingkan dengan orang-orang lain',
                // 200
                'Saya suka menolong orang-orang lain, yang tidak begitu beruntung apabila dibandingkan dengan keadaan saya',
                'Saya suka memperlakukan orang lain dengan ramah dan simpatik',
                'Saya suka menolong orang-orang lain, yang tidak begitu beruntung apabila dibandingkan dengan keadaan saya',
                'Saya suka memaafkan teman-teman saya yang menyakiti hati saya',
                'Saya ingin teman-teman saya mempercayai saya dan menceritakan kesulitan- kesulitan mereka kepada saya',
                'Saya suka bepergian melihat-lihat daerah pedalaman',
                'Saya suka mengikuti mode baru',
                'Saya ingin mengalami pembaharuan dan perubahan dalam kehidupan saya sehari-hari',
                'Saya suka bereksperimen dalam mencoba hal-hal yang baru',
                'Saya suka mengikuti mode-mode baru',
                'Saya suka menyelesaikan setiap pekerjaan atau tugas yang telah saya mulai',
                // 210
                'Saya ingin bekerja berjam-jam tanpa diganggu',
                'Saya suka mengerjakan teka-teki dan memcahkan persoalan-persoalan sampai selesai',
                'Saya ingin menyelesaikan pekerjaan satu persatu sebelum memulai yang lain',
                'Saya ingin menghindarkan diganggu bila saya sedang bekerja',
                'Saya suka ikut dalam aktivitas-aktivitas sosial bersama-sama dengan orang- orang dari lawan jenis saya',
                'Saya mempunyai keinginan untuk mencium orang yang menarik dari lawan jenis saya',
                'Saya mudah jatuh cinta pada seseorang dari lawan jenis saya',
                'Saya suka mendengarkan atau menceritakan lelucon-lelucon yang terutama berkisar soal seks',
                // 220
                'Saya suka mendengarkan atau menceritakan lelucon-lelucon yang terutama berkisar soal seks',
                'Saya suka membaca berita-berita surat kabar tentang pembunuhan-pembunuhan dan lain-lain perbuatan kekerasan',
                'Saya rasanya ingin mengecam seseorang di muka umum bila orang itu patut menerimanya',
                'Saya rasanya ingin menghardik orang lain bila saya berbeda pendapat dengan mereka',
                'Rasa rasanya ingin membalas dendam bila seseorang menghina saya',
                'Saya rasanya ingin memperolok-olok orang-orang yang melakukan hal-hal yang saya anggap bodoh'
            ];



        $nilai = ['A', 'B'];

        for ($id_soal = 351; $id_soal < 576; $id_soal++) {
            // A
            $questions = [
                [
                    'question_id' => $id_soal,
                    'choice' => $nilai[0],
                    'value' => $pilihanA[$id_soal - 351],
                    'order'  => 1
                ],
                [
                    'question_id' => $id_soal,
                    'choice' => $nilai[1],
                    'value' => $pilihanB[$id_soal - 351],
                    'order'  => 2
                ]
            ];
            foreach ($questions as $question) {
                QuestionChoice::query()->create($question);
            };
        }

        dump('Question Choice EPPS : ' . QuestionChoice::query()->whereHas('question.session.type', fn ($q) => $q->where('name', 'EPPS'))->count());
    }
}
